### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by ghost** [powderblue/sf-continent-country-type#7]
Hi,

When I'm trying to install the bundle using the command you gave :

> composer require powderblue/sf-continent-country-type

I get the following error :

> [InvalidArgumentException]
  Could not find a matching version of package powderblue/sf-continent-country-type. Check the package spelling, your version constr
  aint and that the package is available in a stability which matches your minimum-stability (stable).

Any idea on what am I doing wrong? :-)

**Comment by danbettles** [comment]
Hiya!

Could you send me your `composer.json`, please?  I wonder if there's a conflict between some dependencies.  In the mean time, I'll double-check that command.

Thanks 👍

**Comment by ghost** [comment]
Hi!

Sure, here is the content of my **composer.json**:
`{
	"license" : "proprietary",
	"type" : "project",
	"require" : {
		"php": ">=7.3",
		"ext-curl": ">=7.3",
		"ext-dom": ">=2.9.9",
		"ext-gd": ">=2.1.0",
		"ext-intl": ">=7.3",
		"ext-mbstring": ">=1.3.2",
		"ext-sodium": ">=7.2",
		"ext-yaml": ">=2.0.4",
		"doctrine/doctrine-bundle": "^1.10.3",
		"doctrine/doctrine-cache-bundle": "^1.2",
		"doctrine/doctrine-migrations-bundle": "^1.0",
		"doctrine/orm": "^2.5",
		"doctrine/phpcr-odm": "1.4.*",
		"eluceo/ical": "^0.15.0",
		"exercise/htmlpurifier-bundle": "2.0.4",
		"friendsofsymfony/elastica-bundle": "^5.1",
		"friendsofsymfony/jsrouting-bundle": "2.5.1",
		"friendsofsymfony/rest-bundle": "^2.3",
		"friendsofsymfony/user-bundle": "~2.0",
		"gushphp/to-inline-style-email-bundle": "^1.5",
		"hslavich/oneloginsaml-bundle": "^1.5",
		"incenteev/composer-parameter-handler": "^2.0",
		"jackalope/jackalope-doctrine-dbal": "1.3.*",
		"jms/serializer-bundle": "^2.4.4",
		"joshpme/doctrine-encrypt-bundle": "^4.0",
		"knplabs/knp-markdown-bundle": "^1.7",
		"knplabs/knp-menu-bundle": "^2.1",
		"knplabs/knp-paginator-bundle": "^2.8",
		"knplabs/knp-snappy-bundle": "^1.6",
		"leafo/scssphp": "^0.7.2",
		"onelogin/php-saml": "^3.4",
		"paragonie/halite": ">=4.3",
		"paragonie/sodium_compat": ">=1.5",
		"patchwork/jsqueeze": "^2.0",
		"robertotru/to-inline-style-email-bundle": "^1.5",
		"sensio/framework-extra-bundle": "^5.5",
		"stof/doctrine-extensions-bundle": "^1.3",
		"symfony/asset": "^4.0",
		"symfony/console": "^4.0",
		"symfony/dotenv": "^4.4",
		"symfony/error-handler": "^4.0",
		"symfony/expression-language": "^4.0",
		"symfony/finder": "^4.4",
		"symfony/flex": "^1.5",
		"symfony/form": "^4.0",
		"symfony/framework-bundle": "^4.0",
		"symfony/intl": "4.4.*",
		"symfony/mailer": "^4.4",
		"symfony/monolog-bundle": "^3.5",
		"symfony/orm-pack": "^1.0",
		"symfony/polyfill-apcu": "^1.0",
		"symfony/profiler-pack": "^1.0",
		"symfony/security-bundle": "^4.0",
		"symfony/security-csrf": "^4.0",
		"symfony/serializer": "^4.4",
		"symfony/swiftmailer-bundle": "^3.4",
		"symfony/translation": "^4.0",
		"symfony/twig-pack": "^1.0",
		"symfony/validator": "^4.0",
		"symfony/yaml": "^4.4",
		"twig/extensions": "^1.5",
		"vich/uploader-bundle": "^1.6",
		"willdurand/js-translation-bundle": "^2.6",
		"yectep/phpspreadsheet-bundle": "^0.1.0"
	},
	"require-dev" : {
		"doctrine/data-fixtures" : "^1.2",
		"doctrine/doctrine-fixtures-bundle" : "^3.3",
		"fzaninotto/faker" : "^1.9",
		"phpunit/phpunit" : "^8",
		"symfony/maker-bundle" : "^1.14",
		"symfony/phpunit-bridge" : "^3.4",
		"symfony/webpack-encore-bundle" : "^1.7.2"
	},
	"autoload" : {
		"psr-4" : {
			"App\\" : "src/"
		}
	},
	"autoload-dev" : {
		"psr-4" : {
			"Tests\\" : "tests/"
		}
	},
	"config" : {
		"platform" : {
			"php" : "7.3"
		},
		"preferred-install" : {
			"*" : "dist"
		},
		"sort-packages" : true
	},
	"conflict" : {
		"symfony/symfony" : "*"
	},
	"extra" : {
		"symfony" : {
			"allow-contrib" : true,
			"require" : "4.4.*"
		}
	}
}
`

Thanks alot for your answer. :-)

**Comment by danbettles** [comment]
It appears we hadn't added the package to Packagist.  Didn't realise, sorry: we must have been cheating all this time 😛

Package is registered with Packagist, so the command should now work 👍
